name: geospatial-env
channels:
  - conda-forge
dependencies:
  - awscli
  - boto3
  - ipykernel
  - vim
  - wget
  - python=3.10
  - numpy
  - pandas
  - rioxarray
  - rasterio
  - geopandas
  - matplotlib
 